id: IB3A4EA64
legacy_id: PF83CE998
ocr_import_info:
  bdrc_scan_id: W1KG12514
  source: bdrc
  ocr_info:
    timestamp: '2022-03-15T06:29:44'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:30:54.043409+00:00'
last_modified: 2022-08-31 11:31:18.961788
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12514
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12514
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཀའ་གདམས་གླེགས་བམ་ལས་བཏུས་པའི་ཆོས་སྐོར།
  author: རྒྱལ་བའི་འབྱུང་གནས།
statistics:
  ocr_word_mean_confidence_index: 0.9796070673339138
  ocr_word_median_confidence_index: 0.99
quality: null
bases:
  I1KG12518:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12518
      total_pages: 503
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12518.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9796070673339138
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
